language: node_js
node_js:
  - "node"

install:
  - npm install uglify-es -g
script:
  - mkdir ./minified
  - uglifyjs kazel.js -o ./minified/kazel.min.js
  - uglifyjs kazel-filters.js -o ./minified/kazel-filters.min.js
  - uglifyjs KazelList.js -o ./minified/KazelList.min.js
deploy:
  - provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: minified/*
  skip_cleanup: true
  name: "kazel-stable"
  on:
    tags: true
  - provider: npm
  email: "kosimst@gmail.com"
  api_key: $NPM_TOKEN
  on:
    tags: true
  skip_cleanup: true
  name: kazel
  file_glob: true
  file: minified/*
